version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all
    ignore:
      - dependency-name: chalk
